### ISSUE TITLE
Make the repo citable

### ISSUE THREAD

**Issue by otizonaizit** [wichmann-lab/python-psignifit#219]
We need a DOI for the repo, so that the code can be cited when used in scientific publications

**Comment by lschwetlick** [comment]
Hey, seems like its best to do with Zenodo. Whoever owns the repo (@FelixWichmann ?) may need to allow access.

**Comment by otizonaizit** [comment]
I am am admin. How do I allow access?

**Comment by lschwetlick** [comment]
It said that it would send a request to the owner...?

**Comment by otizonaizit** [comment]
> It said that it would send a request to the owner...?

It did. I allowed access. It should work now.

**Comment by lschwetlick** [comment]
For some reason it's not showing up. Just to be clear you did this? :
https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization

**Comment by otizonaizit** [comment]
> For some reason it's not showing up. Just to be clear you did this? : https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization

Yes, it looks like this:

![image](https://github.com/user-attachments/assets/f0a506ca-d327-47ad-9dcd-6626491ad955)

and:

![image](https://github.com/user-attachments/assets/43ea4ce0-888c-47e1-b333-b37f1e87ccd4)

maybe you need admin rights on this repo? I'll make you admin right now.

**Comment by lschwetlick** [comment]
Still doesnt work. Could you make me a "member" of the organization wichman-lab? I think thats the problem, I'm an "outside collaborator", so the organization repos do not get synced through my account?

**Comment by otizonaizit** [comment]
I invited you

**Comment by lschwetlick** [comment]
It works now, Hooray!

So now, when we create a release, Zenodo will automatically download a .zip-ball of each new release and register a DOI. "After your first release, a DOI badge that you can include in GitHub README will appear next to your repository below." It seems we will get the doi only once we make a new release.

**Comment by guillermoaguilar** [comment]
Do we also need a CITATION file? I've seen this file in citable repos before... when present github also shows it on the right, "how to cite this repo" or something.

**Comment by otizonaizit** [comment]
Yes, we need that file, but I think we first need the DOI, so that we can put it in that file. If I understand @lschwetlick correctly, zenodo gives a DOI to a release, not to the repo in general. So we have to update that file _after_ each new release

**Comment by pberkes** [comment]
My ORCID number: https://orcid.org/0000-0002-2827-3911
Tiziano's: https://orcid.org/0000-0002-7199-7456
Lisa's: https://orcid.org/0000-0003-3356-8324
David's (I think, there's no content): https://orcid.org/0000-0001-5507-3731

I don't have an opinion on author's order... shouldn't it match what's on the Zenodo page? https://zenodo.org/records/14750244

**Comment by guillermoaguilar** [comment]
OK all IDs added in the PR.

> I don't have an opinion on author's order... shouldn't it match what's on the Zenodo page? https://zenodo.org/records/14750244

That got pulled automatically, from the commits I suppose. And I guess with a CITATION file that list gets overwritten.

**Comment by otizonaizit** [comment]
Thanks for the ORCID. Regarding author order: it's fine with me any way, alphabetical or historical or effort based :)
In a couple of these orderings I am either first or last author, eheh :)

**Comment by guillermoaguilar** [comment]
Close by #234
